packages_common:
  - vim
  - git
  - curl
  - htop
  - lsb-release
timezone: "America/Lima"
default_scripts_path: "/opt/scripts"
audit_report_path: "/var/log/audit_ansible"
ssh_authorized_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI...usuario1"
vault_file: vault.yml  # Referencia a variables cifradas
