---
# Tareas principales del rol base
# Este archivo incluye las tareas específicas según la plataforma

- name: Incluir tareas de Linux
  ansible.builtin.include_tasks: linux/main.yml
  when: ansible_facts['os_family'] in ['Debian', 'RedHat']

- name: Incluir tareas de Windows
  ansible.builtin.include_tasks: windows/main.yml
  when: ansible_facts['os_family'] == 'Windows'