---
- name: Conectarse al servidor vCenter
  hosts: localhost
  gather_facts: no
  collections:
    - community.vmware

  vars:
    vcenter_hostname: "IP_DEL_VCENTER"
    vcenter_username: "USUARIO_VCENTER"
    vcenter_password: "CONTRASEÑA_VCENTER"
    validate_certs: no

  tasks:
    - name: Obtener información del vCenter
      community.vmware.vmware_about_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
      register: vcenter_info

    - name: Mostrar información del vCenter
      debug:
        var: vcenter_info
